console.log("my first console project");
var first_name="archit ";
var last_name="patel";
var full_name = first_name.concat(last_name);
console.log(full_name);
var a=10;
var b=5;
var add = a + b;
console.log(add);
var c=13;
var d=2;
var subtract = c - d;
console.log(subtract);
var c=12;
var d=3;
var multiply = c * d;
console.log(multiply);
var c=16;
var d=4;
var divide = c / d;
console.log(divide);